Unbalanced Commanders 2.0 (#2820)
* Added core and arm unbacom

evolution paths aren't implimented yet during testing period.

* Added armada, legion, and cortex

evolution's completed for the custom unitdefs I made for the individual unit evolutions.  Also, a gadget that allows legion commanders to build mobile units faster. Here's what yet needs doing:

1. Names aren't displaying properly.

2. D gun for Armada and Cortex commanders aren't categorized properly, they do full damage to other commanders and the level2-10 units aren't immune to dgun.

3. Need to edit existing commander unitdefs for corcom, armcom, and legcomlvl4 to evolve into added unbacom units when modoption enabled.

4. Gotta make a modoption or something that edits the evolution time def in legcom, legcomlvl2, and legcomlvl 3 to be 210 instead of 600 to match the rest of unbacom units.

Edit gadget such that instead of quitting when unbacom is disabled, it quits if no units with relevant unitdefs are logged by the gadget workertime_boost.

* Broken alldefs

Not sure what I did wrong here, but when I add my modoptions code to alldefs as seen in this change it crashes the game during loading.

* more fixes

modoptions now works, so with unbacom enabled in lobby settings the evolutions will integrate with existing commanders

fixed some description and name issues

* Update gui_info.lua

* replaced silly descriptions

more serious now.

* Tweaked unit evolution times

increased from 3.5 minutes to 4 minutes per evolution, they were outpacing normal unit progression vs BARbs

* Fixed workertime_boost bug

Found and fixed a bug with workertime_boost related to failing to pass "if builderID == "number""

should work as expected now

* fixed conflict I hope

* balancing for core and arm coms

improved laser for corcom by disabling collision with heaps and corpses. Otherwise its role as a frontliner was compromised due to laser weapon emitter height. Also improved target reacquisition speed to make better use of DPS

nerfed the armada commander's reload speed. It was firing too fast to fit the shoot>cloak>retreat>decloak>shoot routine.

* balancing legion commanders

spawn rate was too high for lobber dgun, needed to reduce the number. Also, could cause lag by spamming units.

Added a new unit to act in place of lobber that has its own unit count limit so that only 60 can exist per player at a time.  This is called babyleglob

it's identical except that it only has 100 HP and no metal cost and no corpse/heap. That way infinite metal can't be conjured into existance through dgun-reclaim loops.

* further balancing

added health regen values to armada units

buffed damage for both to be more viable against units expected at their tiers

made armada com faster so that it can hit and RUN more effectively

* Added  drones to legcomlvl8-10

They perch atop the shoulders. Spawn rate increases with level.

* buff baby legion lobbers

Restored to their original HP because during testing they were consistently useless because they'd die too soon to affect anything.

* Version 2 complete

Added various weapons and improvements to the commanders. Balanced a little big between the factions.

Buffed Legion's D-gun lob-launcher to be more useful throughout the game. Increased unitcap for babyleglob's up to 90 from 60 to allow more damage against big targets.

Reworked Core and Arm commanders completely. They now have more and better weapons.

Changed lobby modoptions so that you can set your own evolution speed (with a tooltip recommendation of 4 for 4 minutes)

This is ready for playtesting. With the asymmetical design of the factions, it's difficult to judge how balanced they are without trying it in real games.

* Delete gadg

* Delete luarules/gadgets/unit_evolution.lua

I finally found the friggin button

* changed modoptions method

looks better now

* Fixed tooltip for modoptions

Fixed tooltip for modoptions

* Added back in unit evolution

from main repo. I didn't realize deleting it from my fork would request deletion in main.

* tweak default evolution time

From my playtesting vs normal barbs, the commanders were slightly too powerful for the timeframe they were available.

* Update modoptions.lua, switch enable/disable unbacom to bool

Co-authored-by: thehobojoe <the.hobo.joe@gmail.com>

* Update gamedata/alldefs_post.lua unbacom>bool

Co-authored-by: thehobojoe <the.hobo.joe@gmail.com>

* unit_workertime_boost.lua enable check to bool

Co-authored-by: thehobojoe <the.hobo.joe@gmail.com>

* added customparams.isunbacom

for modoptions and other code-stuff to simplify things

* not namechecks, customparams.isunbacom checks

yeah, way fewer lines of code. Makes my little boy heart feel clean

* removed spring.echo debug stuff

* moved legion unbacom to Legion folder

this eliminates infolog spam complaining about unavailable build options. This also makes it so legion unbacom's don't load when legion is disabled.

* remove energyupeep infolog spam

removed energyupkeep = 0, unitdef as it doesn't do anything and causes numerous error entries in infolog

* workertime boost bugfix

Found a way to cheese the gadget. if you created a unit that triggered boost and then immediately built another non-boost-triggering unit, it would remain boosted. Now that's fixed. I cannot find any other cheese for now.

Addressed some of Robert the Epie's design concerns and removed bughunting leftover code.

It's better structured now for future expansion as well.

* remove redundant Spring.GetUnitDefID

* Add param to unit_carrier_spawner gadget

this is to fix the problem where a cloaked retreating armcom's EMP tumbleweeds dock instead of doing their job as a radar distraction.

Now any carrier that doesn't want "hold fire" to dock their drones can do so with the added "holdfireradius" weapon param.

https://youtu.be/UqVyQFfEh2c

* add holdfireradius for arm com drones

https://youtu.be/Qk3FXUfGNfc exhibits new behavior. Added customparam weapondef so that when the commander cloaks to retreat and hold fire, the distracting tumbleweed drones don't dock.

* increased corpse health, legcom dgun imprvmnt

dgun spreads out forces farther, making it more difficult to kill them instantly with AOE attacks
Also made the range more consistent

Corpses were being destroyed immediately upon death toward the T3 phase, increased the health of corpses to give the chance to resurrect commanders

* buffed emp dmg, improve drone targetting

To better distract enemies, baby emp tumbleweeds decloak when near enemies. This should cause enemies autotargetting to prioritize them over the commander when cloaked.

Improved targetting by swapping weapon [5] drone pointer for weapon [1] shortgun. The first weapon slot turns out to be used for targetting as per the unit_carrier_spawner gadget.

Also, either this update or the last update buffed HP of the Arm commander to be same as other factions as it's too punishing and makes them incapable of surviving late game hit and run

* removed avoidground = false from eyelaser

so that the commander doesn't stop while shooting into the ground with "fight" command

* armada longgun range buff, shortgun dmg buff

was too short range, wouldn't survive lategame.

shortgun didn't do nearly enough damage

* fix  babyarmvader selfd explosion type

* delete unused armcom model

* increase builderboost legcom

* fix uncommon workertime boost bug

Sometimes would complain in infolog:

Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=UnitCmdDone trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_workertime_boost.lua"]:66: bad argument #1 to 'remove' (table expected, got number)
stack traceback:
	[C]: in function 'remove'
	[string "LuaRules/Gadgets/unit_workertime_boost.lua"]:66: in function 'UnitCmdDone'
	[string "LuaRules/gadgets.lua"]:1624: in function <[string "LuaRules/gadgets.lua"]:1622>
	(tail call): ?

* Tumbleweeds push commander around less

* fix icons

* fix names

* balance shield regen

the regen was just too damn strong!

Shield has 1.5x capacity as previous, but 1/2 the regen speed as previous.

It takes 30 seconds to recharge from 0 to full. This forces an attack>retreat>attack loop for core commander gameplay

---------

Co-authored-by: thehobojoe <the.hobo.joe@gmail.com>